### PR TITLE
Fixes client crash on server disconnect

### LINKED ISSUE #24: When the server disconnects, clients should be booted to Lobby
Like the title says.

Right now, when the client closes the game for any reason, and a client is present, the client is stuck in a broken game, instead of getting booted to the lobby.

I don't know if you were aware of this issue, but thought I'd mention it, just in case you weren't.

### PR DESCRIPTION
**Pull request by mclark4386**
Closes #24 

*was looking for the game in the wrong place and not stopping the network clock

### CODE REVIEW

**Comment by Dobbelsteen** [comment]
Nice catch, but not a complete fix (see my comment in the code)

**Comment by mclark4386** [comment]
Good call! Yeah that felt a bit hacky to me, but was how it was so hadn't really thought through a better way. I actually took it one set farther with this commit and added a helper function to the network script to handle all the clearing of it's data... fixed a bug even(leftover sprite if you start a new game in what was the client).

**Comment by Dobbelsteen** [comment]
Tested it, works 60% of the time, all the time (first crash might've been caused by something I did, other 2 test runs went fine)

**Comment by mclark4386** [comment]
I noticed a wave of merges. Anything I need to do to make this ready to merge? (Just resolved the conflict introduced via the player names and added that data to the clear)

**Comment by mclark4386** [comment]
rebased...

**Pull request merged**
