### PR TITLE
Event bus (senders, listeners, payload), link pushables to open doors with the help of Events and the event bus

### LINKED ISSUE #8: Push block door
Door that only opens if a specific block in a dungeon has been pushed. No art for blocks yet so simple programmer art is sufficient (unless you wanna draw something)

You can probably check if the player's push animation is playing for a certain amount of time against the block. Count how long a player is colliding with the block, and then move it when it reaches a threshold.

I don't think we have door sprites either, if you wanna do this ask in the Discord.

### PR DESCRIPTION
**Pull request by Dobbelsteen**
So I've done quite a few things in this PR in order to make stuff work.

Minor features:
- Door scene object, that can be locked and unlocked via a function
- Pushables emit a signal when they are done moving

Major feature:

## Event bus singleton

This guy delegates the events. Very small and simple.
Event senders can notify the event bus with an event_name and payload
The bus then forwards these events to any listener who cares (based on event_name) and sends them **only the payload**

## Event
There's 2 types of events: Senders and Listeners (they use the same root node "Event" though)
An event can be both a listener and sender at the same time

To add an event, simply make it a child of any node you want to interact with

In the actual implementation, I extended the Event node, and made an event_unlock node, which also accepts an **event_key_id**, also to demonstrate how you can easily make custom events with various properties.
In this case, **event_key_id** is used to link doors with pushables.
I also think these ids have to be unique across the world right now, is this a feature or a bug? You decide. You can also make events unique across scenes with an event_name prefix or something, which would solve this "problem"

### Sender

sender

Sender uses the following script variables:

- event_name: Identifier of the event
- is_sender: whether or not this event is a sender, this is how we define a sender, so it should be true
- trigger_signal: signal that should be present on the **parent** on this event, the event will trigger upon this signal sending the event_name with payload to the event_bus

### Listener

listener

Listeners use a few other variables

- event_name; see above
- is_listener: pretty straightforward..
- listen_function: This is the important one, this function will get triggered on the **parent** by any event with the above defined event_name, along with the payload. It's up to the listener to decide if it wants to act

## Possible problems

The only thing a Node needs to send an event, is a signal
To listen to an event, you don't need any code changes, just have a function that can be called and accepts the payload parameter and attach a listener-event to a node

I wanted to make the events as decoupled as possible from the nodes they interact with, but this comes with a few potential problems if we're not careful.

- events rely on hardcoded function values. If events rely on a certain function, or signal to be present, and it gets renamed in a refactoring or something, then the link has to updated. The game won't crash, but the event probably won't get triggered/acted upon
- a solution would be to define a predefined function/signal, to listen to and send events; and stick to that. We probably want to send the event_name along with it then, but that's a small change
- same goes for signals, but those are probably less likely to get changed, still, something to keep in mind
- Right now, the payload is computed entirely within the event. It does have access to its parent, so we should be able to get any information we want
- Just realised that events are limited to the active scenes. But they can be easily hooked up to the global_game_state, once there is such a thing, to set certain flags

## Bonus:
- Due to the way that pushables get synced over the server, events that get triggered by pushables are also synced (meaning, doors are in sync right now)
- Sadly, once doors have other means of being opened, they won't be in sync, but that's a problem for the future.
- There is a small block puzzle in the testmap to showcase the new stuffs

Resolves #8 and maybe even #9, but I haven't tried adding an event to monsters yet. Should be pretty easy to do now actually.

Enjoy.

### CODE REVIEW

**Comment by fornclake** [comment]
This is incredible. I've familiarized myself with the basic usage of assigning events to objects, and it seems to be very user friendly. I will have to do a little bit more research as to how I can add more events.

Will it be possible to add multiple event senders that have to be completed to trigger the listener? As in, can we assign multiple enemies to an event so that a single door can open? I can't think of other uses for multiple senders at the moment, so perhaps what we can do instead is create an object that detects that all enemies in the room are dead to send the event.

Either way, awesome work! Are you part of the Discord? We were trying to figure out who you were a little while ago, haha.

**Comment by Dobbelsteen** [comment]
Haha, thanks and you're welcome :)

No, I'm not on your discord yet, but I might hop in there some day soon.

I had been thinking about this stuff some more, and figured I'm basically emulating the emit_signal / connect system that's already in place, sooooo, might have gone overkill.
Then again, I kinda like this implementation more because it's more explicit and visible in the editor.

I'm also considering making it a plugin, so that events can be attached as a resource, instead of a child, and might have some other advantages, but I'm gonna ponder a bit more on that tomorrow.

To answer your question:
> Will it be possible to add multiple event senders that have to be completed to trigger the listener? As in, can we assign multiple enemies to an event so that a single door can open?

I would make a new event, called EventCounter or whatever.
It exposes a count_required integer and count_step or something

The sender simply sends the count_step (with increment value as payload for example)
Alternatively, the sender could attempt to get a step value from the parent, but that's less robust and prone to bugs. We can change the value for each parent in the inspector anyway.

Every time the listener gets an event, increment the counter by the payload, when counter reaches count_required, do the thing on the parent.

Attach senders to monsters (and add a death signal to the monsters if that's not there yet to listen to), attach a listener to the door(s), done :)

You could also add a more generic event that keeps track of the monsters in the room and acts upon that, there's a lot of ways to do it I imagine, this is just what comes to mind right now

Also, thank you for this as well. It's been very enjoyable to work on something like this

**Comment by fornclake** [comment]
I'm wondering if it might be better to just make it use signals. You can already expose NodePaths as export variables, so each door or object can have a trigger assigned to it and have an export that states what signal is connected. It might be an easier concept to grasp.

This method is very robust as is and already works with networking, so I'm not gonna worry about it.

I hope you join the Discord! We've been discussing a ton of things there that might not be talked about anywhere on GitHub.

**Comment by Dobbelsteen** [comment]
Yup, signals are probably simpler.

Sometimes you lose track of the forest for the trees.
It's been a fun mind bender regardless

**Pull request merged**
